db_bo2span_database_name=spandb_dev
db_bo2span_host_name=10.0.117.41
db_bo2span_password=Bsi12345
db_bo2span_port=3306
db_bo2span_user_name=span
db_mis_database_name=HouseKeeping
db_mis_host_name=10.0.17.15
db_mis_password=rempoa1!
db_mis_port=1433
db_mis_schema=dbo
db_mis_user_name=t24rempoa
db_skn_host_name=x.x.x.x
db_skn_name=DBSPK
db_skn_password=Bsm_sp4n
db_skn_port=1433
db_skn_schema=dbo
db_skn_user_name=app_span
ftp_span_host_name=10.0.17.13
ftp_span_port=21
ftp_span_password=Bsm123
ftp_span_user_name=ftpspan
ftp_core_host_name=10.0.17.13
ftp_core_port=21
ftp_core_password=Bsm123
ftp_core_user_name=ftpspan

# String uploadPath = propertiesMap.properties.getProperty("path_bo2span_span_sp2d_get");
# String archivePath = propertiesMap.properties.getProperty("path_bo2span_span_sp2d_archive");
# String toolsPath = propertiesMap.properties.getProperty("path_bo2span_commands");

path_bo2span_apps_home=/apps/bo2span
path_bo2span_backup=/apps/bo2span/data/span/backup
path_bo2span_config=/apps/bo2span/data/config
path_bo2span_home=/home/span
path_bo2span_span_reject_approval_archive=/apps/bo2span/data/span/reject_approval/archive
path_bo2span_span_reject_approval_put=/apps/bo2span/data/span/reject_apporval/put
path_bo2span_span_rekening_koran_archive=/apps/bo2span/data/span/rekening_koran/archive
path_bo2span_span_rekening_koran_put=/apps/bo2span/data/span/rekening_koran/put
path_bo2span_span_acknowledge_archive=/apps/bo2span/data/span/acknowledge/archive
path_bo2span_span_acknowledge_put=/apps/bo2span/data/span/acknowledge/put
path_bo2span_span_bank_statement_archive=/apps/bo2span/data/span/bank_statement/archive
path_bo2span_span_bank_statement_put=/apps/bo2span/data/span/bank_statement/put
path_bo2span_span_sorbor_archive=/apps/bo2span/data/span/sorbor/archive
path_bo2span_span_sorbor_put=/apps/bo2span/data/span/sorbor/put
path_bo2span_span_sp2d_archive=/apps/bo2span/data/span/sp2d/archive
path_bo2span_span_sp2d_get=/apps/bo2span/data/span/sp2d/get
path_bo2span_span_sp2d_put=/apps/bo2span/data/span/sp2d/put
path_bo2span_core_bank_statement_archive=/apps/bo2span/data/core/bank_statement/archive
path_bo2span_core_bank_statement_log=/apps/bo2span/data/core/bank_statement/log
path_bo2span_core_bank_statement_request=/apps/bo2span/data/core/bank_statement/request
path_bo2span_core_bank_statement_response=/apps/bo2span/data/core/bank_statement/response
path_bo2span_core_enquiry_account_archive=/apps/bo2span/data/core/enquiry_account/archive
path_bo2span_core_enquiry_account_log=/apps/bo2span/data/core/enquiry_account/log
path_bo2span_core_enquiry_account_request=/apps/bo2span/data/core/enquiry_account/request
path_bo2span_core_enquiry_account_response=/apps/bo2span/data/core/enquiry_account/response
path_bo2span_core_enquiry_account_user_request=/apps/bo2span/data/core/enquiry_account/user_request
path_bo2span_core_enquiry_account_user_response=/apps/bo2span/data/core/enquiry_account/user_response
path_bo2span_core_posting_service_archive=/apps/bo2span/data/core/posting_service/archive
path_bo2span_core_posting_service_log=/apps/bo2span/data/core/posting_service/log
path_bo2span_core_posting_service_request=/apps/bo2span/data/core/posting_service/request
path_bo2span_core_posting_service_response=/apps/bo2span/data/core/posting_service/response
path_span_ftp_inbound_bs=/Inbound/BS
path_span_ftp_inbound_lhp=/Inbound/LHP
path_span_ftp_inbound_sorbor=/Inbound/SORBOR
path_span_ftp_inbound_sp2d_ack=/Inbound/SP2D_ACK
path_span_ftp_inbound_spt_ack=/Inbound/SPT_ACK
path_span_ftp_outbound_sp2d=/Outbound/SP2D
path_span_ftp_outbound_spt=/Outbound/SPT
path_core_ftp_span_backup=/backup
path_core_ftp_span_process_in_online=/process/in/online
path_core_ftp_span_process_out=/out
url_core_tws=http://10.0.116.25:8180/iBSM_TWS/services
url_core_tws_password=123123
url_core_tws_user_name=DEVSPAN
path_bo2span_web=/apps/bo2span/tools/bo2span_web
path_bo2span_commands=/apps/bo2span/tools/bo2span_commands
path_bo2span_services=/apps/bo2span/tools/bo2span_services
info_bo2span_user_name=BO2-H2H
info_bo2span_status=JAR-000
#Digital Signature

ds_set_prefix_soap=soapenv
ds_receive_properties=receiver.properties
ds_sender_properties=sender.properties
ds_user_name=taxfrontend1
ds_password=
ds_alias=taxfrontend1
ds_acknowledge_put=/home/span/apps/bo2span/data/span/acknowledge/put
ds_bank_code=525451000990
