org.apache.ws.security.crypto.provider=org.apache.ws.security.components.crypto.Merlin
org.apache.ws.security.crypto.merlin.keystore.type=jks
org.apache.ws.security.crypto.merlin.keystore.password=Fi20N17a
org.apache.ws.security.crypto.merlin.keystore.alias=core.span.depkeu.go.id
org.apache.ws.security.crypto.merlin.keystore.file=bo2span.syariahmandiri.co.id.jks