# Endpoint webservice T24
bifast.accountEnquiry.endpointUrl=http://10.0.118.39:5442/gateway/msrBifastAccountEnquiryOutgoing/1.0/accountEnquiry
bifast.creditTransfer.endpointUrl=http://10.0.118.39:5442/gateway/msrBifastCreditTransferOutgoing/1.0/creditTransfer
#  API key / token jika dibutuhkan oleh server
bifast.apiKey=ea9cf8d8-b955-40ff-9c85-a5e0bfb0d30c

# Timeout (milidetik)
bifast.connectTimeoutMs=10000
bifast.readTimeoutMs=100000