# Endpoint webservice T24
t24.endpointUrl=http://apigw-uat-cbs-corp.bankbsi.co.id:4015/ws/coreR24AllServices/1.0

# SOAPAction header (kosongkan jika server tidak mewajibkan)
t24.soapAction=

# Kredensial WebRequestCommon
t24.userName=USERIDSSPP
t24.password=Bsi12345
t24.company=

# Opsional: API key / token jika dibutuhkan oleh server
t24.apiKey=48578186-b7c9-4520-8a5e-bde96c8c8ab5

# Timeout (milidetik)
t24.connectTimeoutMs=10000
t24.readTimeoutMs=60000