org.apache.ws.security.crypto.provider=org.apache.ws.security.components.crypto.Merlin
org.apache.ws.security.crypto.merlin.keystore.type=jks
org.apache.ws.security.crypto.merlin.keystore.password=Fi20N17a
org.apache.ws.security.crypto.merlin.keystore.alias=taxfrontend1
org.apache.ws.security.crypto.merlin.keystore.file=/Users/fhartanto/apps/bo2span/data/config/bo2span.syariahmandiri.co.id.jks
